[package]
name = "viewrs"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.12.1", features = ["svg"] }
quick-xml = "0.36.0"

[profile.release]
strip = true
opt-level = "z"
lto = true
